/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_main (void)
{
  GtkWidget *window_main;
  GdkPixbuf *window_main_icon_pixbuf;
  GtkWidget *table_main;
  GtkWidget *menubar;
  GtkWidget *menuitem_file;
  GtkWidget *menuitem_file_menu;
  GtkWidget *separator_file_01;
  GtkWidget *menu_quit;
  GtkWidget *menuitem_help;
  GtkWidget *menuitem_help_menu;
  GtkWidget *separator_help_01;
  GtkWidget *menu_about;
  GtkWidget *table3;
  GtkWidget *image_temp;
  GtkWidget *image_cpu;
  GtkWidget *label_cpustatus;
  GtkWidget *label_tempstatus;
  GtkWidget *statusbar;
  GtkWidget *combo_speedvalues;
  GtkWidget *combo_entry1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  window_main = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (window_main, "window_main");
  gtk_window_set_title (GTK_WINDOW (window_main), "gtk-cpuspeedy");
  window_main_icon_pixbuf = create_pixbuf ("cpu.png");
  if (window_main_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window_main), window_main_icon_pixbuf);
      gdk_pixbuf_unref (window_main_icon_pixbuf);
    }

  table_main = gtk_table_new (4, 1, FALSE);
  gtk_widget_set_name (table_main, "table_main");
  gtk_widget_show (table_main);
  gtk_container_add (GTK_CONTAINER (window_main), table_main);

  menubar = gtk_menu_bar_new ();
  gtk_widget_set_name (menubar, "menubar");
  gtk_widget_show (menubar);
  gtk_table_attach (GTK_TABLE (table_main), menubar, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  menuitem_file = gtk_menu_item_new_with_mnemonic ("_File");
  gtk_widget_set_name (menuitem_file, "menuitem_file");
  gtk_widget_show (menuitem_file);
  gtk_container_add (GTK_CONTAINER (menubar), menuitem_file);

  menuitem_file_menu = gtk_menu_new ();
  gtk_widget_set_name (menuitem_file_menu, "menuitem_file_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem_file), menuitem_file_menu);

  separator_file_01 = gtk_menu_item_new ();
  gtk_widget_set_name (separator_file_01, "separator_file_01");
  gtk_widget_show (separator_file_01);
  gtk_container_add (GTK_CONTAINER (menuitem_file_menu), separator_file_01);
  gtk_widget_set_sensitive (separator_file_01, FALSE);

  menu_quit = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_set_name (menu_quit, "menu_quit");
  gtk_widget_show (menu_quit);
  gtk_container_add (GTK_CONTAINER (menuitem_file_menu), menu_quit);

  menuitem_help = gtk_menu_item_new_with_mnemonic ("_Help");
  gtk_widget_set_name (menuitem_help, "menuitem_help");
  gtk_widget_show (menuitem_help);
  gtk_container_add (GTK_CONTAINER (menubar), menuitem_help);

  menuitem_help_menu = gtk_menu_new ();
  gtk_widget_set_name (menuitem_help_menu, "menuitem_help_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem_help), menuitem_help_menu);

  separator_help_01 = gtk_menu_item_new ();
  gtk_widget_set_name (separator_help_01, "separator_help_01");
  gtk_widget_show (separator_help_01);
  gtk_container_add (GTK_CONTAINER (menuitem_help_menu), separator_help_01);
  gtk_widget_set_sensitive (separator_help_01, FALSE);

  menu_about = gtk_menu_item_new_with_mnemonic ("_About");
  gtk_widget_set_name (menu_about, "menu_about");
  gtk_widget_show (menu_about);
  gtk_container_add (GTK_CONTAINER (menuitem_help_menu), menu_about);

  table3 = gtk_table_new (2, 2, FALSE);
  gtk_widget_set_name (table3, "table3");
  gtk_widget_show (table3);
  gtk_table_attach (GTK_TABLE (table_main), table3, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  image_temp = create_pixmap (window_main, "thermometer.png");
  gtk_widget_set_name (image_temp, "image_temp");
  gtk_widget_show (image_temp);
  gtk_table_attach (GTK_TABLE (table3), image_temp, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  image_cpu = create_pixmap (window_main, "cpu.png");
  gtk_widget_set_name (image_cpu, "image_cpu");
  gtk_widget_show (image_cpu);
  gtk_table_attach (GTK_TABLE (table3), image_cpu, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  label_cpustatus = gtk_label_new ("<none>");
  gtk_widget_set_name (label_cpustatus, "label_cpustatus");
  gtk_widget_show (label_cpustatus);
  gtk_table_attach (GTK_TABLE (table3), label_cpustatus, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  label_tempstatus = gtk_label_new ("<none>");
  gtk_widget_set_name (label_tempstatus, "label_tempstatus");
  gtk_widget_show (label_tempstatus);
  gtk_table_attach (GTK_TABLE (table3), label_tempstatus, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  statusbar = gtk_statusbar_new ();
  gtk_widget_set_name (statusbar, "statusbar");
  gtk_widget_show (statusbar);
  gtk_table_attach (GTK_TABLE (table_main), statusbar, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo_speedvalues = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_speedvalues)->popwin),
                     "GladeParentKey", combo_speedvalues);
  gtk_widget_set_name (combo_speedvalues, "combo_speedvalues");
  gtk_widget_show (combo_speedvalues);
  gtk_table_attach (GTK_TABLE (table_main), combo_speedvalues, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 2, 4);

  combo_entry1 = GTK_COMBO (combo_speedvalues)->entry;
  gtk_widget_set_name (combo_entry1, "combo_entry1");
  gtk_widget_show (combo_entry1);

  g_signal_connect_swapped ((gpointer) window_main, "delete_event",
                            G_CALLBACK (quit),
                            GTK_OBJECT (window_main));
  g_signal_connect ((gpointer) menu_quit, "activate",
                    G_CALLBACK (quit),
                    NULL);
  g_signal_connect ((gpointer) menu_about, "activate",
                    G_CALLBACK (on_button_about_pressed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_main, window_main, "window_main");
  GLADE_HOOKUP_OBJECT (window_main, table_main, "table_main");
  GLADE_HOOKUP_OBJECT (window_main, menubar, "menubar");
  GLADE_HOOKUP_OBJECT (window_main, menuitem_file, "menuitem_file");
  GLADE_HOOKUP_OBJECT (window_main, menuitem_file_menu, "menuitem_file_menu");
  GLADE_HOOKUP_OBJECT (window_main, separator_file_01, "separator_file_01");
  GLADE_HOOKUP_OBJECT (window_main, menu_quit, "menu_quit");
  GLADE_HOOKUP_OBJECT (window_main, menuitem_help, "menuitem_help");
  GLADE_HOOKUP_OBJECT (window_main, menuitem_help_menu, "menuitem_help_menu");
  GLADE_HOOKUP_OBJECT (window_main, separator_help_01, "separator_help_01");
  GLADE_HOOKUP_OBJECT (window_main, menu_about, "menu_about");
  GLADE_HOOKUP_OBJECT (window_main, table3, "table3");
  GLADE_HOOKUP_OBJECT (window_main, image_temp, "image_temp");
  GLADE_HOOKUP_OBJECT (window_main, image_cpu, "image_cpu");
  GLADE_HOOKUP_OBJECT (window_main, label_cpustatus, "label_cpustatus");
  GLADE_HOOKUP_OBJECT (window_main, label_tempstatus, "label_tempstatus");
  GLADE_HOOKUP_OBJECT (window_main, statusbar, "statusbar");
  GLADE_HOOKUP_OBJECT (window_main, combo_speedvalues, "combo_speedvalues");
  GLADE_HOOKUP_OBJECT (window_main, combo_entry1, "combo_entry1");

  gtk_window_add_accel_group (GTK_WINDOW (window_main), accel_group);

  return window_main;
}

GtkWidget*
create_window_about (void)
{
  GtkWidget *window_about;
  GdkPixbuf *window_about_icon_pixbuf;
  GtkWidget *table2;
  GtkWidget *hseparator2;
  GtkWidget *hbuttonbox2;
  GtkWidget *button_ok;
  GtkWidget *label_copyright;
  GtkWidget *label_app_url;
  GtkWidget *label_app_description;
  GtkWidget *label_app_name;
  GtkWidget *image_cpuspeedy;

  window_about = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (window_about, "window_about");
  gtk_container_set_border_width (GTK_CONTAINER (window_about), 5);
  gtk_window_set_title (GTK_WINDOW (window_about), "About gtk-cpuspeedy");
  gtk_window_set_position (GTK_WINDOW (window_about), GTK_WIN_POS_MOUSE);
  gtk_window_set_resizable (GTK_WINDOW (window_about), FALSE);
  window_about_icon_pixbuf = create_pixbuf ("cpu.png");
  if (window_about_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window_about), window_about_icon_pixbuf);
      gdk_pixbuf_unref (window_about_icon_pixbuf);
    }

  table2 = gtk_table_new (7, 1, FALSE);
  gtk_widget_set_name (table2, "table2");
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (window_about), table2);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator2, "hseparator2");
  gtk_widget_show (hseparator2);
  gtk_table_attach (GTK_TABLE (table2), hseparator2, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 5);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox2, "hbuttonbox2");
  gtk_widget_show (hbuttonbox2);
  gtk_table_attach (GTK_TABLE (table2), hbuttonbox2, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_SHRINK), 0, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox2), GTK_BUTTONBOX_END);

  button_ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_set_name (button_ok, "button_ok");
  gtk_widget_show (button_ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button_ok);
  GTK_WIDGET_SET_FLAGS (button_ok, GTK_CAN_DEFAULT);

  label_copyright = gtk_label_new ("<span size=\"small\">(C) 2004 Gabriele Giorgetti</span>");
  gtk_widget_set_name (label_copyright, "label_copyright");
  gtk_widget_show (label_copyright);
  gtk_table_attach (GTK_TABLE (table2), label_copyright, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 5);
  gtk_label_set_use_markup (GTK_LABEL (label_copyright), TRUE);
  gtk_label_set_justify (GTK_LABEL (label_copyright), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label_copyright), 0.51, 0.5);

  label_app_url = gtk_label_new ("<span size=\"medium\" underline=\"single\">http://cpuspeedy.sourceforge.net</span>");
  gtk_widget_set_name (label_app_url, "label_app_url");
  gtk_widget_show (label_app_url);
  gtk_table_attach (GTK_TABLE (table2), label_app_url, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 2);
  GTK_WIDGET_SET_FLAGS (label_app_url, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label_app_url), TRUE);
  gtk_label_set_selectable (GTK_LABEL (label_app_url), TRUE);

  label_app_description = gtk_label_new ("gtk-cpuspeedy is a GTK+ frontend for cpuspeedy, a simple program to control the speed and the voltage of CPUs on the fly.\n");
  gtk_widget_set_name (label_app_description, "label_app_description");
  gtk_widget_show (label_app_description);
  gtk_table_attach (GTK_TABLE (table2), label_app_description, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  GTK_WIDGET_SET_FLAGS (label_app_description, GTK_CAN_FOCUS);
  gtk_label_set_justify (GTK_LABEL (label_app_description), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (label_app_description), TRUE);
  gtk_label_set_selectable (GTK_LABEL (label_app_description), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label_app_description), 0.57, 0.5);

  label_app_name = gtk_label_new ("<span size=\"xx-large\" weight=\"bold\"> gtk-cpuspeedy 0.4.0 </span>");
  gtk_widget_set_name (label_app_name, "label_app_name");
  gtk_widget_show (label_app_name);
  gtk_table_attach (GTK_TABLE (table2), label_app_name, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 5);
  GTK_WIDGET_SET_FLAGS (label_app_name, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label_app_name), TRUE);
  gtk_label_set_justify (GTK_LABEL (label_app_name), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (label_app_name), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label_app_name), 0.56, 0.5);

  image_cpuspeedy = create_pixmap (window_about, "cpu.png");
  gtk_widget_set_name (image_cpuspeedy, "image_cpuspeedy");
  gtk_widget_show (image_cpuspeedy);
  gtk_table_attach (GTK_TABLE (table2), image_cpuspeedy, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 5);

  g_signal_connect_swapped ((gpointer) button_ok, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (window_about));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_about, window_about, "window_about");
  GLADE_HOOKUP_OBJECT (window_about, table2, "table2");
  GLADE_HOOKUP_OBJECT (window_about, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (window_about, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (window_about, button_ok, "button_ok");
  GLADE_HOOKUP_OBJECT (window_about, label_copyright, "label_copyright");
  GLADE_HOOKUP_OBJECT (window_about, label_app_url, "label_app_url");
  GLADE_HOOKUP_OBJECT (window_about, label_app_description, "label_app_description");
  GLADE_HOOKUP_OBJECT (window_about, label_app_name, "label_app_name");
  GLADE_HOOKUP_OBJECT (window_about, image_cpuspeedy, "image_cpuspeedy");

  return window_about;
}

